apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: olivercw/resultserver
        name: resultserver
        ports:
        - containerPort: 80
        resources: {}
        envFrom:
        - configMapRef:
            name: server-config
        - secretRef:
            name: mysql-secret
        # env:
        # - name: MYSQL_PASSWORD
        #   value: Clarusway_1
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql-svc
