apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: olivercw/webserver
        name: webserver
        ports:
        - containerPort: 80
        resources: {}
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: server-config
        # env:
        # - name: MYSQL_PASSWORD
        #   value: Clarusway_1
        # - name: MYSQL_USER
        #   value: clarus
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql-svc
